package ultralist

import (
	"fmt"

	"github.com/fatih/color"
)

// Usage : displays how to use todolist
func Usage() {
	blue := color.New(color.FgBlue)
	cyan := color.New(color.FgCyan)
	yellow := color.New(color.FgYellow)

	blueBold := blue.Add(color.Bold)

	fmt.Printf("Ultralist v%s, a simple, command line based, GTD-style task manager\n", VERSION)

	blueBold.Println("\nAdding todos")
	fmt.Println("  the 'a' command adds todos.")
	fmt.Println("  You can also optionally specify a due date.")
	fmt.Println("  Specify a due date by putting 'due <date>' at the end, where <date> is in (tod|today|tom|tomorrow|mon|tue|wed|thu|fri|sat|sun)")
	fmt.Println("\n  Examples for adding a todo:")
	yellow.Println("\tultralist a Meeting with @bob about +importantPrject due today")
	yellow.Println("\tultralist a +work +verify did @john fix the build\\?")

	blueBold.Println("\nListing todos")
	fmt.Println("  When listing todos, you can filter and group the output.")
	fmt.Println()

	fmt.Println("  ultralist l due (tod|today|tom|tomorrow|overdue|this week|next week|last week|mon|tue|wed|thu|fri|sat|sun|none)")
	fmt.Println("  ultralist l overdue")

	cyan.Println("  Filtering by date:")
	fmt.Println()
	yellow.Println("\tultralist l due tod")
	fmt.Println("\tlists all todos due today")
	fmt.Println()
	yellow.Println("\tultralist l due tom")
	fmt.Println("\tlists all todos due tomorrow")
	fmt.Println()
	yellow.Println("\tultralist l due mon")
	fmt.Println("\tlists all todos due monday")
	fmt.Println()
	yellow.Println("\tultralist l overdue")
	fmt.Println("\tlists all todos where the due date is in the past")
	fmt.Println()
	yellow.Println("\tultralist agenda")
	fmt.Println("\tultralist all todos where the due date is today or in the past")
	fmt.Println()

	fmt.Println("  ultralist l completed (tod|today|this week)")
	cyan.Println("  Filtering by date:")
	fmt.Println()

	yellow.Println("\tultralist l completed (tod|today)")
	fmt.Println("\tlists all todos that were completed today")
	fmt.Println()
	yellow.Println("\tultralist l completed this week")
	fmt.Println("\tlists all todos that were completed this week")
	fmt.Println()

	cyan.Println("  Grouping:")
	fmt.Println("  You can group todos by context or project.")
	yellow.Println("\tultralist l by c")
	fmt.Println("\tlists all todos grouped by context")
	fmt.Println()
	yellow.Println("\tultralist l by p")
	fmt.Println("\tlists all todos grouped by project")
	fmt.Println()

	cyan.Println("  Grouping and filtering:")
	fmt.Println("  Of course, you can combine grouping and filtering to get a nice formatted list.")
	fmt.Println()
	yellow.Println("\tultralist l due today by c")
	fmt.Println("\tlists all todos due today grouped by context")
	fmt.Println()
	yellow.Println("\tultralist l +project due this week by c")
	fmt.Println("\tlists all todos due today for +project, grouped by context")
	fmt.Println()
	yellow.Println("\tultralist l @frank due tom by p")
	fmt.Println("\tlists all todos due tomorrow concerining @frank for +project, grouped by project")
	fmt.Println()

	blueBold.Println("\nCompleting and uncompleting ")
	fmt.Println("Complete and Uncomplete a todo by its Id:")
	fmt.Println()
	yellow.Println("\tultralist c 33")
	fmt.Println("\tCompletes a todo with id 33")
	fmt.Println()
	yellow.Println("\tultralist uc 33")
	fmt.Println("\tUncompletes a todo with id 33")
	fmt.Println()

	blueBold.Println("\nPrioritizing")
	fmt.Println("Todos have a priority flag, which will make them bold when listed.")
	fmt.Println()
	yellow.Println("\tultralist p 33")
	fmt.Println("\tPrioritizes a todo with id 33")
	fmt.Println()
	yellow.Println("\tultralist up 33")
	fmt.Println("\tUn-prioritizes a todo with id 33")
	fmt.Println()
	yellow.Println("\tultralist l p")
	fmt.Println("\tlist all priority todos")
	fmt.Println()

	blueBold.Println("\nArchiving")
	fmt.Println("You can archive todos once they are done, or if you might come back to them.")
	fmt.Println("By default, todo will only show unarchived todos.")
	fmt.Println()
	yellow.Println("\tultralist ar 33")
	fmt.Println("\tArchives a todo with id 33")
	fmt.Println()
	yellow.Println("\tultralist ac")
	fmt.Println("\tArchives all completed todos")
	fmt.Println()
	yellow.Println("\tultralist l archived")
	fmt.Println("\tlist all archived todos")
	fmt.Println()

	blueBold.Println("\nEditing due dates")
	yellow.Println("\tultralist e 33 due mon")
	fmt.Println("\tEdits the todo with 33 and sets the due date to this coming Monday")
	fmt.Println()
	yellow.Println("\tultralist e 33 due none")
	fmt.Println("\tEdits the todo with 33 and removes the due date")
	fmt.Println()

	blueBold.Println("\nExpanding existing todos")
	yellow.Println("\tultralist ex 39 +final: read physics due mon, do literature report due fri")
	fmt.Println("\tRemoves the todo with id 39, and adds following two todos")
	fmt.Println()

	blueBold.Println("\nDeleting")
	yellow.Println("\tultralist d 33")
	fmt.Println("\tDeletes a todo with id 33")
	fmt.Println()

	blueBold.Println("\nManipulating notes")
	yellow.Println("\tultralist ln")
	fmt.Println("\tlists all todos with their notes")
	yellow.Println("\tultralist an 12 check http://this.web.site")
	fmt.Println("\tAdds notes \"check http://this.web.site\" to the todo with id 12")
	fmt.Println()
	yellow.Println("\tultralist n 12")
	fmt.Println("\tLists notes of the todo with id 12")
	fmt.Println()
	yellow.Println("\tultralist dn 12 3")
	fmt.Println("\tDeletes the 3rd note of the todo with id 12")
	fmt.Println()
	yellow.Println("\tultralist en 12 3 check http://that.web.site")
	fmt.Println("\tEditing the 3rd note of the todo with id 12 to \"http://that.web.site\" ")
	fmt.Println()

	blueBold.Println("\nGarbage Collection")
	yellow.Println("\tultralist gc")
	fmt.Println("\tDeletes all archived todos.")
	fmt.Println()

	fmt.Println("Ultralist was lovingly crafted by Grant Ammons (https://twitter.com/gammons).")
	fmt.Println("For full documentation, please visit http://docs.ultralist.io")
}
